image: node:19.7.0

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - cd backend && npm install
  script:
    # are we in a docker-executor
    - if [ -f /.dockerenv ]; then echo "docker-executor"; fi
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml

deploy-prod:
  stage: deploy
  script:
    - |
      git status
      git checkout main
      git pull origin main
      cd backend
      make start
  environment: production
  # rules:
  #   - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
  #     when: never
  #   - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
